-- MySQL Script generated by MySQL Workbench
-- Mon Oct  9 22:18:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Geographical DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Geographical DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table Countries
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Countries (
  countryID INT UNSIGNED NOT NULL ,
  country_name VARCHAR(45) NOT NULL , -- 'This is the combination of all the countries, and not including the cities.',
  country_capital VARCHAR(45) NOT NULL,
  country_surface INT NOT NULL,
  country_time_zone VARCHAR(45) NOT NULL,
  country_largest_city VARCHAR(45) NOT NULL,
  PRIMARY KEY (countryID));



-- -----------------------------------------------------
-- Table Cities
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Cities (
  cityID INT UNSIGNED NOT NULL ,
  city_name VARCHAR(45) NOT NULL , -- 'This is the subset of all the cities, and not including the countries.',
  city_population INT NOT NULL,
  city_surface INT NOT NULL,
  PRIMARY KEY (cityID));



-- -----------------------------------------------------
-- Table Countries+
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Countriess (
  placeID INT UNSIGNED NOT NULL ,
  countriesID INT UNSIGNED NULL, -- 'This is the combination of all the places, including the cities and the countries.',
  place_name VARCHAR(45) NOT NULL,
  place_time_zone VARCHAR(45) NOT NULL,
  surface VARCHAR(45) NOT NULL,
  place_country VARCHAR(45) NOT NULL,
  cityID INT UNSIGNED NULL,
  PRIMARY KEY (placeID),
  CONSTRAINT country_name
  FOREIGN KEY (countriesID)
  REFERENCES Countries (countryID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT cityn_name
  FOREIGN KEY (cityID)
  REFERENCES Cities (cityID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table Timezone
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Timezone (
  timezoneID INT UNSIGNED NOT NULL ,
  timezone_name VARCHAR(45) NULL , -- 'This is the combination of all the places.',
  PRIMARY KEY (timezoneID));


-- -----------------------------------------------------
-- Table TimezoneChangerbyPlace
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TimezoneChangerbyPlace (
  by_place INT UNSIGNED NOT NULL,
  by_timezone INT UNSIGNED NOT NULL , -- 'This table is selector of timezone, it connects the places and their timezone.',
  CONSTRAINT place_timezone
  FOREIGN KEY (by_place)
  REFERENCES Countriess (placeID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT timezone
  FOREIGN KEY (by_timezone)
  REFERENCES Timezone (timezoneID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table TimezoneChangerbyCity
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TimezoneChangerbyCity (
  cityID INT UNSIGNED NOT NULL,
  timezoneID INT UNSIGNED NOT NULL , -- 'This table is selector of timezone, it connects the city (and the city itself only, not including the country) and their timezone.',
  CONSTRAINT cityID
  FOREIGN KEY (cityID)
  REFERENCES Cities (cityID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT timezoneID
  FOREIGN KEY (timezoneID)
  REFERENCES Timezone (timezoneID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table CapitalChanger
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CapitalChanger (
  capitalID INT UNSIGNED NOT NULL ,
  countryID INT UNSIGNED NOT NULL , -- 'This table is the selector of capital, it connects all the countries(and only the countries themselves) and their capital city. ',
  CONSTRAINT city
  FOREIGN KEY (capitalID)
  REFERENCES Cities (cityID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT country
  FOREIGN KEY (countryID)
  REFERENCES Countries (countryID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table TimezoneChangerbyCountry
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TimezoneChangerbyCountry (
  countryid INT UNSIGNED NOT NULL,
  timezoneid INT UNSIGNED NOT NULL , -- 'This table is selector of timezone, it connects the country (and the country itself only, not including the country) and their timezone.',
  CONSTRAINT country
  FOREIGN KEY (countryid)
  REFERENCES Countries (countryID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT timezone
  FOREIGN KEY (timezoneid)
  REFERENCES Timezone (timezoneID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table LargestCityChanger
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS LargestCityChanger (
  cityID INT UNSIGNED NOT NULL,
  countryID INT UNSIGNED NOT NULL , -- 'This is the table is a selector of largest city, and it will connect the country and their biggest city.',
  CONSTRAINT city
  FOREIGN KEY (cityID)
  REFERENCES Cities (cityID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT country
  FOREIGN KEY (countryID)
  REFERENCES Countries (countryID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION);
